"use client";

import { useMemo, useState } from "react";

type Customer = { id: string; full_name: string; identification: string | null };
type Vehicle = { id: string; customer_id: string; plate: string; brand: string; model: string; current_mileage: number | null };
type Service = { id: string; name: string; price: number };
type Product = { id: string; category: string; brand: string | null; name: string; viscosity: string | null; sale_price: number; stock: number };
type Profile = { id: string; full_name: string; role: string };
type Line = { id: string; quantity: number };

export function OrderForm({ action, customers, vehicles, services, products, profiles, defaultCustomerId, defaultVehicleId }: {
  action: (formData: FormData) => void | Promise<void>;
  customers: Customer[]; vehicles: Vehicle[]; services: Service[]; products: Product[]; profiles: Profile[]; defaultCustomerId?: string; defaultVehicleId?: string;
}) {
  const inferredCustomer = defaultCustomerId || vehicles.find((v)=>v.id===defaultVehicleId)?.customer_id || "";
  const [customerId, setCustomerId] = useState(inferredCustomer);
  const [vehicleId, setVehicleId] = useState(defaultVehicleId || "");
  const [serviceLines, setServiceLines] = useState<Line[]>([]); const [productLines, setProductLines] = useState<Line[]>([]);
  const customerVehicles = vehicles.filter((vehicle)=>vehicle.customer_id===customerId);
  const selectedVehicle = vehicles.find((vehicle)=>vehicle.id===vehicleId);
  const total = useMemo(() => serviceLines.reduce((sum,line)=>sum+(services.find((s)=>s.id===line.id)?.price ?? 0)*line.quantity,0) + productLines.reduce((sum,line)=>sum+(products.find((p)=>p.id===line.id)?.sale_price ?? 0)*line.quantity,0), [serviceLines, productLines, services, products]);

  function toggle(lines: Line[], setLines: (lines: Line[])=>void, id: string, checked: boolean) { setLines(checked ? [...lines, { id, quantity: 1 }] : lines.filter((line)=>line.id!==id)); }
  function quantity(lines: Line[], setLines: (lines: Line[])=>void, id: string, value: number) { setLines(lines.map((line)=>line.id===id ? { ...line, quantity: Math.max(0.01, value || 1) } : line)); }

  return <form action={action} className="space-y-6">
    <input type="hidden" name="services_json" value={JSON.stringify(serviceLines)} /><input type="hidden" name="products_json" value={JSON.stringify(productLines)} />
    <section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">1. Cliente y vehículo</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm font-medium">Cliente *</span><select name="customer_id" value={customerId} onChange={(e)=>{setCustomerId(e.target.value);setVehicleId("");}} className="w-full rounded-lg border px-3 py-2" required><option value="">Seleccione un cliente</option>{customers.map((c)=><option key={c.id} value={c.id}>{c.full_name}{c.identification ? ` · ${c.identification}` : ""}</option>)}</select></label><label className="space-y-2"><span className="text-sm font-medium">Vehículo *</span><select name="vehicle_id" value={vehicleId} onChange={(e)=>setVehicleId(e.target.value)} className="w-full rounded-lg border px-3 py-2" required disabled={!customerId}><option value="">Seleccione un vehículo</option>{customerVehicles.map((v)=><option key={v.id} value={v.id}>{v.plate} · {v.brand} {v.model}</option>)}</select></label><label className="space-y-2"><span className="text-sm font-medium">Kilometraje de ingreso</span><input name="mileage" type="number" min={0} step={1} defaultValue={selectedVehicle?.current_mileage ?? ""} key={selectedVehicle?.id || "none"} className="w-full rounded-lg border px-3 py-2" /></label><label className="space-y-2"><span className="text-sm font-medium">Técnico asignado</span><select name="assigned_employee_id" className="w-full rounded-lg border px-3 py-2" defaultValue=""><option value="">Sin asignar</option>{profiles.map((p)=><option key={p.id} value={p.id}>{p.full_name} · {p.role}</option>)}</select></label></div></section>
    <section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">2. Servicios</h2><p className="mt-1 text-sm text-slate-500">Selecciona uno o varios servicios.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{services.map((service)=>{const line=serviceLines.find((l)=>l.id===service.id);return <div key={service.id} className="rounded-lg border p-4"><label className="flex items-start gap-3"><input type="checkbox" checked={!!line} onChange={(e)=>toggle(serviceLines,setServiceLines,service.id,e.target.checked)} className="mt-1"/><span className="flex-1"><span className="font-medium">{service.name}</span><span className="block text-sm text-slate-500">${service.price.toFixed(2)}</span></span></label>{line&&<input type="number" min="0.01" step="0.01" value={line.quantity} onChange={(e)=>quantity(serviceLines,setServiceLines,service.id,Number(e.target.value))} className="mt-3 w-28 rounded-lg border px-3 py-2" aria-label={`Cantidad ${service.name}`}/>}</div>})}</div></section>
    <section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">3. Productos</h2><p className="mt-1 text-sm text-slate-500">Aceites, filtros, aditivos e insumos.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{products.map((product)=>{const line=productLines.find((l)=>l.id===product.id);return <div key={product.id} className="rounded-lg border p-4"><label className="flex items-start gap-3"><input type="checkbox" checked={!!line} onChange={(e)=>toggle(productLines,setProductLines,product.id,e.target.checked)} className="mt-1"/><span className="flex-1"><span className="font-medium">{[product.brand,product.name,product.viscosity].filter(Boolean).join(" ")}</span><span className="block text-sm text-slate-500">{product.category} · ${product.sale_price.toFixed(2)} · stock {product.stock}</span></span></label>{line&&<input type="number" min="0.01" max={product.stock || undefined} step="0.01" value={line.quantity} onChange={(e)=>quantity(productLines,setProductLines,product.id,Number(e.target.value))} className="mt-3 w-28 rounded-lg border px-3 py-2" aria-label={`Cantidad ${product.name}`}/>}</div>})}</div></section>
    <section className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">4. Observaciones y total</h2><textarea name="observations" rows={4} placeholder="Observaciones de recepción, novedades del vehículo..." className="mt-4 w-full rounded-lg border px-3 py-2"/><div className="mt-5 flex flex-col gap-4 border-t pt-5 sm:flex-row sm:items-end sm:justify-between"><div className="text-sm text-slate-500"><p>El precio mostrado es referencial.</p><p>El servidor vuelve a consultar los precios en Supabase antes de guardar.</p></div><div className="text-right"><p className="text-sm text-slate-500">Total de la orden</p><p className="text-3xl font-bold">${total.toFixed(2)}</p><button className="mt-3 rounded-lg bg-slate-900 px-5 py-2.5 font-medium text-white">Crear orden de servicio</button></div></div></section>
  </form>;
}
