import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { deleteOrder } from "../actions";
const labels: Record<string,string>={pending:"Pendiente",assigned:"Asignada",in_progress:"En proceso",completed:"Finalizada",delivered:"Entregada",cancelled:"Cancelada"};
export default async function OrderDetailPage({params,searchParams}:{params:{id:string};searchParams:{error?:string;message?:string}}){
  const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/login");
  const {data:order}=await supabase.from("service_orders").select("id, order_number, status, mileage, observations, subtotal, tax, total, created_at, completed_at, assigned_employee_id, customers!service_orders_customer_id_fkey(id, full_name, identification, phone), vehicles!service_orders_vehicle_id_fkey(id, plate, brand, model, year), profiles!service_orders_assigned_employee_id_fkey(full_name)").eq("id",params.id).single();if(!order)notFound();
  const [{data:serviceLines},{data:productLines}]=await Promise.all([supabase.from("order_services").select("id, quantity, unit_price, subtotal, services(name)").eq("order_id",params.id),supabase.from("order_products").select("id, quantity, unit_price, subtotal, products(name, brand, viscosity, category)").eq("order_id",params.id)]);
  const remove=deleteOrder.bind(null,order.id);const customer:any=order.customers,vehicle:any=order.vehicles,technician:any=order.profiles;
  return <section className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Link href="/dashboard/ordenes" className="text-sm text-slate-600 hover:underline">← Volver a órdenes</Link><h1 className="mt-2 text-3xl font-bold">OS-{String(order.order_number).padStart(5,"0")}</h1><p className="mt-1 text-slate-500">{labels[order.status]??order.status} · {new Date(order.created_at).toLocaleString("es-EC")}</p></div><div className="flex gap-2"><Link href={`/dashboard/ordenes/${order.id}/editar`} className="rounded-lg border bg-white px-4 py-2 font-medium">Editar / estado</Link>{["pending","cancelled"].includes(order.status)&&<form action={remove}><button className="rounded-lg border border-red-200 bg-red-50 px-4 py-2 font-medium text-red-700">Eliminar</button></form>}</div></div>
  {searchParams.message&&<div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{searchParams.message}</div>}{searchParams.error&&<div className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{searchParams.error}</div>}
  <div className="grid gap-6 lg:grid-cols-3"><article className="rounded-xl border bg-white p-6 lg:col-span-2"><h2 className="text-lg font-semibold">Recepción</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Detail label="Cliente" value={customer?.full_name}/><Detail label="Identificación" value={customer?.identification}/><Detail label="Vehículo" value={`${vehicle?.plate??""} · ${vehicle?.brand??""} ${vehicle?.model??""}`}/><Detail label="Kilometraje" value={order.mileage!=null?`${order.mileage} km`:null}/><Detail label="Técnico" value={technician?.full_name}/><Detail label="Estado" value={labels[order.status]??order.status}/><div className="sm:col-span-2"><Detail label="Observaciones" value={order.observations}/></div></dl></article><article className="rounded-xl border bg-slate-900 p-6 text-white"><p className="text-sm text-slate-300">Total</p><p className="mt-2 text-4xl font-bold">${Number(order.total).toFixed(2)}</p><div className="mt-5 space-y-2 text-sm text-slate-300"><p>Subtotal: ${Number(order.subtotal).toFixed(2)}</p><p>Impuesto: ${Number(order.tax).toFixed(2)}</p></div></article></div>
  <div className="grid gap-6 lg:grid-cols-2"><Lines title="Servicios" lines={(serviceLines??[]).map((l:any)=>({name:l.services?.name??"Servicio",quantity:Number(l.quantity),unit:Number(l.unit_price),subtotal:Number(l.subtotal)}))}/><Lines title="Productos" lines={(productLines??[]).map((l:any)=>({name:[l.products?.brand,l.products?.name,l.products?.viscosity].filter(Boolean).join(" ")||"Producto",quantity:Number(l.quantity),unit:Number(l.unit_price),subtotal:Number(l.subtotal)}))}/></div>
  <div className="flex flex-wrap gap-3"><Link href={`/dashboard/clientes/${customer?.id}`} className="rounded-lg border bg-white px-4 py-2">Abrir cliente</Link><Link href={`/dashboard/vehiculos/${vehicle?.id}`} className="rounded-lg border bg-white px-4 py-2">Abrir vehículo</Link></div></section>;
}
function Detail({label,value}:{label:string;value:string|null|undefined}){return <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1">{value||"—"}</dd></div>}
function Lines({title,lines}:{title:string;lines:{name:string;quantity:number;unit:number;subtotal:number}[]}){return <article className="rounded-xl border bg-white p-6"><h2 className="text-lg font-semibold">{title}</h2>{lines.length===0?<p className="mt-4 text-sm text-slate-500">Sin registros.</p>:<div className="mt-4 divide-y">{lines.map((line,index)=><div key={`${line.name}-${index}`} className="flex items-center justify-between gap-4 py-3"><div><p className="font-medium">{line.name}</p><p className="text-sm text-slate-500">{line.quantity} × ${line.unit.toFixed(2)}</p></div><p className="font-semibold">${line.subtotal.toFixed(2)}</p></div>)}</div>}</article>}
